### ISSUE TITLE
do animixplay and  gogoanime 

### ISSUE THREAD

**Issue by XxnittanixX** [ByteDream/stream-bypass#3]
animix play?

**Comment by XxnittanixX** [comment]
also i challenge you to make a quick and reliable color picker /screen capture/snip  with cli  commands on windows  

Ill even pay ya

**Comment by ByteDream** [comment]
> also i challenge you to make a quick and reliable color picker /screen capture/snip with cli commands on windows
> 
> Ill even pay ya

i think there is probably already a solution for this out. and if not, you can try using ffmpeg. it can dp all of your requested things besides the color picking

**Comment by ByteDream** [comment]
gogoanime support is partially given. If you choose a video provider which is supported by this addon, it works as it should. I nearly all of the newer gogoanime episodes have doodstream as a video provider, which will be supported in the next version.
animixplay won't get support (in the near future) since it's simply too complex. Multiple streaming providers (it uses gogoanime as well as crunchyroll, probably some more which I haven't noticed too), multiple stream resolutions, ... .
